// -----------------------------------------------------------------------------
// Default preset state. This is the single source of factory values.
//
// Every numeric default here is also declared (with min/max/label/uniform/TD
// destination) in parameterDefinitions.ts. Keep the two in sync: defaults.ts is
// the *values*, parameterDefinitions.ts is the *metadata* that drives the UI and
// the uniform binding.
// -----------------------------------------------------------------------------

import {
  APP_VERSION,
  SCHEMA_VERSION,
  type BeverageDefinition,
  type BeverageId,
  type BeverageMap,
  type PresetState,
} from "../app/types";

export const DEFAULT_RESOLUTION = { width: 1920, height: 1080 };

// Per-beverage palettes and behaviour, following the creative direction in the
// build spec (§6). Colours are sRGB hex; the shader converts to linear.
const BEVERAGES: BeverageMap = {
  americano: {
    label: "Americano",
    colors: {
      primary: "#5A3A22",
      secondary: "#31200F",
      highlight: "#C08A4E",
      shadow: "#160D06",
    },
    rest: {
      restingSpeed: 0.35,
      restingAmplitude: 0.18,
      patternScale: 2.1,
      gradientScale: 1.6,
      gradientDirection: 90,
      noiseScale: 3.0,
      noiseStrength: 0.22,
      domainWarp: 0.25,
      pulseAmount: 0.1,
      pulseSpeed: 0.4,
      luminanceDrift: 0.12,
      edgeActivity: 0.25,
    },
    style: {
      luminance: 0.55,
      density: 0.72,
      edgeSoftness: 0.4,
      internalContrast: 0.62,
      distortion: 0.28,
      horizontalBias: 0.15,
      verticalBias: 0.7,
    },
    active: {
      durationMultiplier: 1.0,
      brightness: 0.6,
      displacement: 0.35,
      spread: 0.4,
      settlingSpeed: 0.7,
    },
  },
  matcha: {
    label: "Matcha",
    colors: {
      primary: "#536B3B",
      secondary: "#A7B77A",
      highlight: "#D8D8A5",
      shadow: "#1E2B19",
    },
    rest: {
      restingSpeed: 0.5,
      restingAmplitude: 0.3,
      patternScale: 1.7,
      gradientScale: 1.2,
      gradientDirection: 0,
      noiseScale: 2.4,
      noiseStrength: 0.3,
      domainWarp: 0.4,
      pulseAmount: 0.2,
      pulseSpeed: 0.35,
      luminanceDrift: 0.2,
      edgeActivity: 0.4,
    },
    style: {
      luminance: 0.68,
      density: 0.5,
      edgeSoftness: 0.6,
      internalContrast: 0.4,
      distortion: 0.35,
      horizontalBias: 0.3,
      verticalBias: 0.3,
    },
    active: {
      durationMultiplier: 1.15,
      brightness: 0.8,
      displacement: 0.3,
      spread: 0.75,
      settlingSpeed: 0.55,
    },
  },
  latte: {
    label: "Latte",
    colors: {
      primary: "#D8C4A6",
      secondary: "#EFE3D0",
      highlight: "#FBF4E8",
      shadow: "#B49B78",
    },
    rest: {
      restingSpeed: 0.28,
      restingAmplitude: 0.16,
      patternScale: 1.2,
      gradientScale: 2.0,
      gradientDirection: 90,
      noiseScale: 1.6,
      noiseStrength: 0.14,
      domainWarp: 0.2,
      pulseAmount: 0.08,
      pulseSpeed: 0.25,
      luminanceDrift: 0.16,
      edgeActivity: 0.18,
    },
    style: {
      luminance: 0.85,
      density: 0.35,
      edgeSoftness: 0.8,
      internalContrast: 0.28,
      distortion: 0.16,
      horizontalBias: 0.6,
      verticalBias: 0.2,
    },
    active: {
      durationMultiplier: 1.2,
      brightness: 0.9,
      displacement: 0.22,
      spread: 0.8,
      settlingSpeed: 0.5,
    },
  },
  espresso: {
    label: "Espresso",
    colors: {
      primary: "#4A2413",
      secondary: "#7A3C1C",
      highlight: "#D9863E",
      shadow: "#1A0C06",
    },
    rest: {
      restingSpeed: 0.7,
      restingAmplitude: 0.22,
      patternScale: 3.2,
      gradientScale: 1.4,
      gradientDirection: 90,
      noiseScale: 4.2,
      noiseStrength: 0.28,
      domainWarp: 0.3,
      pulseAmount: 0.28,
      pulseSpeed: 0.7,
      luminanceDrift: 0.14,
      edgeActivity: 0.5,
    },
    style: {
      luminance: 0.5,
      density: 0.85,
      edgeSoftness: 0.35,
      internalContrast: 0.8,
      distortion: 0.3,
      horizontalBias: 0.2,
      verticalBias: 0.5,
    },
    active: {
      durationMultiplier: 0.8,
      brightness: 0.85,
      displacement: 0.45,
      spread: 0.35,
      settlingSpeed: 0.9,
    },
  },
  coldBrew: {
    label: "Cold Brew",
    colors: {
      primary: "#2E2A33",
      secondary: "#3F3A4A",
      highlight: "#8A93A8",
      shadow: "#120F16",
    },
    rest: {
      restingSpeed: 0.22,
      restingAmplitude: 0.24,
      patternScale: 1.5,
      gradientScale: 1.8,
      gradientDirection: 75,
      noiseScale: 2.0,
      noiseStrength: 0.24,
      domainWarp: 0.5,
      pulseAmount: 0.12,
      pulseSpeed: 0.2,
      luminanceDrift: 0.1,
      edgeActivity: 0.3,
    },
    style: {
      luminance: 0.42,
      density: 0.68,
      edgeSoftness: 0.5,
      internalContrast: 0.55,
      distortion: 0.42,
      horizontalBias: 0.1,
      verticalBias: 0.8,
    },
    active: {
      durationMultiplier: 1.3,
      brightness: 0.6,
      displacement: 0.4,
      spread: 0.45,
      settlingSpeed: 0.4,
    },
  },
};

export function defaultBeverage(id: BeverageId): BeverageDefinition {
  return structuredClone(BEVERAGES[id]);
}

export function createDefaultPreset(): PresetState {
  return {
    schemaVersion: SCHEMA_VERSION,
    appVersion: APP_VERSION,
    presetName: "Initial Rothko Strata",
    savedAt: new Date().toISOString(),
    resolution: { ...DEFAULT_RESOLUTION },
    randomSeed: 18472,
    history: {
      visibleCount: 10,
      maximumCount: 20,
      initialCount: 10,
      randomizeInitialCount: false,
    },
    global: {
      timeScale: 0.16,
      exposure: 1.0,
      saturation: 1.0,
      contrast: 1.0,
      backgroundLuminance: 0.04,
      gradientSoftness: 0.5,
      motionAmount: 1.0,
      horizontalDrift: 0.6,
      driftTurbulence: 0.5,
      sharedFlowScale: 1.4,
      sharedFlowSpeed: 0.3,
      sharedDisplacement: 0.06,
      grainAmount: 0.025,
      bloomAmount: 0.25,
      previewQuality: 1.0,
      pause: false,
    },
    strataLayout: {
      heightVariation: 0.25,
      heightWeighting: 0.5,
      stackCompression: 0.2,
      entryDuration: 1.6,
      exitDuration: 1.8,
      shiftDuration: 1.2,
      easing: 0.7,
      overshoot: 0.12,
      settlingDamping: 0.8,
      boundarySoftness: 0.14,
    },
    interaction: {
      colorBleed: 0.11,
      neighborCoupling: 0.18,
      interactionRadius: 0.12,
      boundaryDisplacement: 0.05,
      sharedFieldInfluence: 0.4,
      edgeContamination: 0.2,
      interactionDecay: 0.6,
      crossLuminance: 0.15,
      boundaryIrregularity: 0.3,
    },
    cascade: {
      duration: 3.5,
      travelDuration: 2.4,
      width: 0.18,
      softness: 0.12,
      peakIntensity: 0.75,
      peakSaturation: 0.3,
      displacement: 0.2,
      neighborDisturbance: 0.3,
      echoCount: 1,
      echoSpacing: 0.6,
      settlingDuration: 4.0,
    },
    queue: {
      minInterval: 0.6,
      overlapAmount: 0.3,
      doubleClickProtection: true,
      doubleClickInterval: 0.25,
    },
    debug: {
      monochrome: false,
      showBoundaries: false,
      showIndices: false,
      showCascadeField: false,
      showFrameRate: true,
      showRenderResolution: true,
      freezeTime: false,
      displaySeeds: false,
    },
    beverages: structuredClone(BEVERAGES),
  };
}
